parameters:
    database_driver:   pdo_mysql
    database_host:     nmotion-server.pp.ciklum.com
    database_port:     ~
    database_name:     nmotion_stage_test
    database_user:     nmotion_stage
    database_password: AQAmzsG9Gj7uSH9y

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       no-reply-test@nmotion.dk
    mailer_password:   mcWB9LyV

    facebook_app_id:   124395924385734
    facebook_secret:   dc763525e278934e44d003331308c672

    locale:            en
    secret:            d9a7f53b978be44f8c8af10c2530444331c28a80
