Nmotion\NmotionBundle\Entity\LogEntry:
    type: entity
    table: nmtn_log_entry
    repositoryClass: Gedmo\Loggable\Entity\Repository\LogEntryRepository
    id:
        id:
            type: integer
            unsigned: true
            primary: true
            nullable: false
            generator:
                strategy: IDENTITY
    fields:
        action:
            type: string
            length: 8
            nullable: false
        loggedAt:
            type: datetime
            nullable: false
            column: logged_at
        objectId:
            type: string
            length: 32
            nullable: true
            column: object_id
        objectClass:
            type: string
            length: 255
            nullable: false
            column: object_class
        version:
            type: integer
            nullable: false
        data:
            type: array
            nullable: true
        username:
            type: string
            length: 255
            nullable: true
    indexes:
        log_class_lookup_idx:
            columns: [object_class]
        log_date_lookup_idx:
            columns: [logged_at]
        log_user_lookup_idx:
            columns: [username]
    options:
        type: InnoDB
    lifecycleCallbacks: {  }
