imports:
    - { resource: parameters/prod.yml }
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver:
            type: array
            #type: memcache
            #host: localhost
        query_cache_driver:
            type: array
            # type: memcache
            # host: localhost
        result_cache_driver:
            type: array
            # type: memcache
            # host: localhost

framework:
    router: { resource: "%kernel.root_dir%/config/routing_prod.yml" }
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
