nmotion_landing_page:
    prefix: /
    resource: "@NmotionLandingPageBundle/Resources/config/routing.yml"
nmotion_nmotion:
    prefix: /
    resource: "@NmotionNmotionBundle/Resources/config/routing.yml"

nmotion_api_v1:
    type:     rest # Required for `RestYamlLoader` to process imported routes
    prefix:   /api/v1
    defaults:  { version: 1 }
    resource: "@NmotionApiBundle/Resources/config/routing.v1.yml"

nmotion_api_v2:
    type:     rest # Required for `RestYamlLoader` to process imported routes
    prefix:   /api/v2
    defaults:  { version: 2 }
    resource: "@NmotionApiBundle/Resources/config/routing.v2.yml"

nmotion_backoffice:
    type:     rest # Required for `RestYamlLoader` to process imported routes
    prefix:   /backoffice
    resource: "@NmotionBackofficeBundle/Resources/config/routing.yml"

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#fos_user_security:
#    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile
#
#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting
#
#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile
