# http://jmsyst.com/libs/serializer/master/reference/yml_reference
Nmotion\NmotionBundle\Entity\RestaurantAdmin:
     exclusion_policy: ALL
     access_type: public_method
     properties:
         restaurant:
             expose: false
             groups: []
