parameters:
#    nmotion_landing_page.example.class: Nmotion\LandingPageBundle\Example

services:
#    nmotion_landing_page.example:
#        class: %nmotion_landing_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
